app_account/urls.py
from django.urls import URLPattern, path
from knox import views as knox_views

from .views import (
    CreateUser,
    LoginView,
    LogoutView,
    confirm_email,
    forgot_password,
    confirm_otp_forgot_password,
    ChangePasswordView,
    reset_password,
    activate_user_account_by_admin,
    PartialUpdateUser,
    GetUserDetails,
    GetAllUsers,
    GetLoginUserDetails,
)

app_name = "app_account"

urlpatterns = [
    path("register/", CreateUser.as_view(), name="register"),
    path("login/", LoginView.as_view(), name="login"),
    # path('logout/', knox_views.LogoutView.as_view(), name='knox_logout'),
    path("logout/", LogoutView.as_view(), name="logout"),
    path(
        "activate-user-account_by_admin/<int:pk>/",
        activate_user_account_by_admin,
        name="activate-user-account_by_admin",
    ),
    path(
        "confirm-email/<str:uidb64>/<str:token>/", confirm_email, name="confirm-email"
    ),
    path("forgot-password/", forgot_password, name="forgot-password"),
    path(
        "confirm-otp-forgot-password/",
        confirm_otp_forgot_password,
        name="confirm-otp-forgot-password",
    ),
    path("reset-password/", reset_password, name="reset-password"),
    path("change-password/", ChangePasswordView.as_view(), name="change-password"),
    path("update/", PartialUpdateUser.as_view(), name="update"),
    path("get-login-user-details/", GetLoginUserDetails.as_view(), name ="get-login-user-details"),
    path("get-all-users/", GetAllUsers.as_view(), name ="get-all-users"),
    path("get-user-details/<int:pk>/", GetUserDetails.as_view(), name ="get-user-details"),

]

app_frontend/urls.py
from django.urls import path
from .views import (
    forgot_password,
    index,
    login,
    forgot_password,
    confirm_otp,
    reset_password,
    enter_new_product,
    add_groups_form,
    add_locations_form,
    add_categories_form,
    add_suppliers_form,
    list_products_page,
    add_units_measure_form,
)

app_name = "app_frontend"


urlpatterns = [
    path("", index, name="index"),
    path("login/", login, name="login"),
    path("forgot-password/", forgot_password, name="forgot-password"),
    path("confirm-otp/", confirm_otp, name="confirm-otp"),
    path("reset-password/", reset_password, name="reset-password"),
    path("new-product/", enter_new_product, name="new-product"),
    path("add-groups-form/", add_groups_form, name="add-groups-form"),
    path("add-locations-form/", add_locations_form, name="add-locations-form"),
    path("add-categories-form/", add_categories_form, name="add-categories-form"),
    path("add-suppliers-form/", add_suppliers_form, name="add-suppliers-form"),
    path("add-units-measure-form/", add_units_measure_form, name="add-units-measure-form"),
    path("list-page/", list_products_page, name="list-page"),
]

app_temp/urls.py
from django.urls import URLPattern, path
from knox import views as knox_views

from .views import (
    TempCreate
)

app_name = "app_temp"

urlpatterns = [
    path("temp-create/", TempCreate.as_view(), name="temp-create"),

]

inventory_core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [ 
    path('api/', include("app_products.urls")),
    path('api/', include("app_account.urls")),
    path('', include("app_frontend.urls")),
    path('api/', include("app_temp.urls")),
    path('admin/', admin.site.urls),
    # path('api/auth/', include('knox.urls')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),                                                 

]


# Adding the static urls
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_frontend/models.py
from django.db import models

# Create your models here.

app_temp/models.py
from django.db import models

# Create your models here.

class SauceModel(models.Model):
    name = models.CharField(max_length=200, blank=True, null=True)



class SandwichModel(models.Model):
    name = models.CharField(max_length=200, blank=True, null=True)
    sauces = models.ManyToManyField(SauceModel)

    class Meta:
        verbose_name_plural = "User Roles"

app_frontend/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    return render(request, "app_frontend/ctemplates/index.html")


def login(request):
    return render(request, "app_frontend/login.html")


def forgot_password(request):
    return render(request, "app_frontend/forgot_password.html")


def confirm_otp(request):
    return render(request, "app_frontend/confirm_otp.html")


def reset_password(request):
    return render(request, "app_frontend/reset_password.html")


def enter_new_product(request):
    return render(request, "app_frontend/enter_new_product.html")


def add_groups_form(request):
    return render(request, "app_frontend/add_groups_form.html")


def add_locations_form(request):
    return render(request, "app_frontend/add_locations_form.html")


def add_categories_form(request):
    return render(request, "app_frontend/add_categories_form.html")


def add_suppliers_form(request):
    return render(request, "app_frontend/add_suppliers_form.html")


def add_units_measure_form(request):
    return render(request, "app_frontend/add_units_measure_form.html")


def list_products_page(request):
    return render(request, "app_frontend/list_products_page.html")

app_frontend/templates/app_frontend/add_categories_form.html
{% extends 'app_frontend/add_forms_base.html' %}
{% load static %}

<!-- title -->
{% block title %}
Add Categories Form
{% endblock title %}

<!-- styles -->
{% block styles %}

{% endblock styles %}


<!-- Details form -->
{% block details-form %}

<div class="form-group">

    <div class="row">

        <div class="col-md-2">
            <label for="list-item-name" class="col-sm-2 control-label">Name</label>
        </div>

        <div class="col-md-10">
            <input type="text" class="form-control" id="list-item-name" placeholder="Categories.." readonly />
        </div>
    </div>
    <div class="row"></div>

    <div class="row" style="margin-top: 10px;">
        <div class="col-md-3">
            <a class="btn btn-success" style="display: none;" id="save-btn" href="javascript:void(0)">Save</a>
        </div>
        <div class="col-md-3">
            <a class="btn btn-danger" style="display: none;" id="cancel-btn" href="javascript:void(0)">Cancel</a>
        </div>
        <div class="col-md-3"></div>
        <div class="col-md-3">
            <a class="btn btn-warning" id="edit-btn" href="javascript:void(0)">Edit</a>
        </div>
    </div>

</div>

{% endblock details-form %}


<!-- New Entry form -->
{% block new-entry-form %}

<div class="form-group">
    <!-- Name Label -->
    <div class="row">
        <label for="list-item-name_input" class="col-sm-1 control-label">Name:</label>
    </div>

    <!-- Name Input field -->
    <div class="row">
        <div class="col-md-12">
            <input type="text" class="form-control" id="list-item-name-input" placeholder="Categories.." />
        </div>

    </div>
</div>

<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <a class="btn btn-warning" id="add-new-list-item" href="javascript:void(0)">Add new Categories</a>
    </div>
    <div class="col-md-3"></div>
</div>

{% endblock new-entry-form %}



{% block scripts %}
<script src="{% static 'app_frontend/js/add_categories_form_script.js' %}"></script>
{% endblock scripts %}

app_frontend/templates/app_frontend/add_groups_form.html
{% extends 'app_frontend/add_forms_base.html' %}
{% load static %}

<!-- title -->
{% block title %}
Add Group Form
{% endblock title %}

<!-- styles -->
{% block styles %}

{% endblock styles %}


<!-- Details form -->
{% block details-form %}

<div class="form-group">

    <div class="row">

        <div class="col-md-2">
            <label for="list-item-name" class="col-sm-2 control-label">Name</label>
        </div>

        <div class="col-md-10">
            <input type="text" class="form-control" id="list-item-name" placeholder="Group.." readonly />
        </div>
    </div>
    <div class="row"></div>

    <div class="row" style="margin-top: 10px;">
        <div class="col-md-3">
            <a class="btn btn-success" style="display: none;" id="save-btn" href="javascript:void(0)">Save</a>
        </div>
        <div class="col-md-3">
            <a class="btn btn-danger" style="display: none;" id="cancel-btn" href="javascript:void(0)">Cancel</a>
        </div>
        <div class="col-md-3"></div>
        <div class="col-md-3">
            <a class="btn btn-warning" id="edit-btn" href="javascript:void(0)">Edit</a>
        </div>
    </div>

</div>

{% endblock details-form %}


<!-- New Entry form -->
{% block new-entry-form %}

<div class="form-group">
    <!-- Name Label -->
    <div class="row">
        <label for="list-item-name_input" class="col-sm-1 control-label">Name:</label>
    </div>

    <!-- Name Input field -->
    <div class="row">
        <div class="col-md-12">
            <input type="text" class="form-control" id="list-item-name-input" placeholder="Group.." />
        </div>

    </div>
</div>

<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <a class="btn btn-warning" id="add-new-list-item" href="javascript:void(0)">Add new Group</a>
    </div>
    <div class="col-md-3"></div>
</div>

{% endblock new-entry-form %}



{% block scripts %}
<script src="{% static 'app_frontend/js/add_groups_form_script.js' %}"></script>
{% endblock scripts %}

app_frontend/templates/app_frontend/add_locations_form.html
{% extends 'app_frontend/add_forms_base.html' %}
{% load static %}

<!-- title -->
{% block title %}
Add Locations Form
{% endblock title %}

<!-- styles -->
{% block styles %}

{% endblock styles %}


<!-- Details form -->
{% block details-form %}

<div class="form-group">

    <div class="row">

        <div class="col-md-2">
            <label for="list-item-name" class="col-sm-2 control-label">Name</label>
        </div>

        <div class="col-md-10">
            <input type="text" class="form-control" id="list-item-name" placeholder="Location.." readonly />
        </div>
    </div>
    <div class="row"></div>

    <div class="row" style="margin-top: 10px;">
        <div class="col-md-3">
            <a class="btn btn-success" style="display: none;" id="save-btn" href="javascript:void(0)">Save</a>
        </div>
        <div class="col-md-3">
            <a class="btn btn-danger" style="display: none;" id="cancel-btn" href="javascript:void(0)">Cancel</a>
        </div>
        <div class="col-md-3"></div>
        <div class="col-md-3">
            <a class="btn btn-warning" id="edit-btn" href="javascript:void(0)">Edit</a>
        </div>
    </div>

</div>

{% endblock details-form %}


<!-- New Entry form -->
{% block new-entry-form %}

<div class="form-group">
    <!-- Name Label -->
    <div class="row">
        <label for="list-item-name_input" class="col-sm-1 control-label">Name:</label>
    </div>

    <!-- Name Input field -->
    <div class="row">
        <div class="col-md-12">
            <input type="text" class="form-control" id="list-item-name-input" placeholder="Location.." />
        </div>

    </div>
</div>

<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <a class="btn btn-warning" id="add-new-list-item" href="javascript:void(0)">Add new Location</a>
    </div>
    <div class="col-md-3"></div>
</div>

{% endblock new-entry-form %}



{% block scripts %}
<script src="{% static 'app_frontend/js/add_locations_form_script.js' %}"></script>
{% endblock scripts %}

app_frontend/templates/app_frontend/add_suppliers_form.html
{% extends 'app_frontend/add_forms_base.html' %}
{% load static %}

<!-- title -->
{% block title %}
Add Suppliers Form
{% endblock title %}

<!-- styles -->
{% block styles %}

{% endblock styles %}


<!-- Details form -->
{% block details-form %}

<div class="form-group">

    <div class="row">

        <div class="col-md-2">
            <label for="list-item-name" class="col-sm-2 control-label">Name</label>
        </div>

        <div class="col-md-10">
            <input type="text" class="form-control" id="list-item-name" placeholder="Supplier.." readonly />
        </div>
    </div>
    <div class="row"></div>

    <div class="row" style="margin-top: 10px;">
        <div class="col-md-3">
            <a class="btn btn-success" style="display: none;" id="save-btn" href="javascript:void(0)">Save</a>
        </div>
        <div class="col-md-3">
            <a class="btn btn-danger" style="display: none;" id="cancel-btn" href="javascript:void(0)">Cancel</a>
        </div>
        <div class="col-md-3"></div>
        <div class="col-md-3">
            <a class="btn btn-warning" id="edit-btn" href="javascript:void(0)">Edit</a>
        </div>
    </div>

</div>

{% endblock details-form %}


<!-- New Entry form -->
{% block new-entry-form %}

<div class="form-group">
    <!-- Name Label -->
    <div class="row">
        <label for="list-item-name_input" class="col-sm-1 control-label">Name:</label>
    </div>

    <!-- Name Input field -->
    <div class="row">
        <div class="col-md-12">
            <input type="text" class="form-control" id="list-item-name-input" placeholder="Supplier.." />
        </div>

    </div>
</div>

<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <a class="btn btn-warning" id="add-new-list-item" href="javascript:void(0)">Add new Supplier</a>
    </div>
    <div class="col-md-3"></div>
</div>

{% endblock new-entry-form %}



{% block scripts %}
<script src="{% static 'app_frontend/js/add_suppliers_form_script.js' %}"></script>
{% endblock scripts %}

app_frontend/templates/app_frontend/confirm_otp.html
{% extends 'accounts_base.html' %}
{% load static %}

{% block title %}Confirm Otp{% endblock title %}
{% block loginActiveStatus %}{% endblock loginActiveStatus %}
{% block displayImage %}
    <img src="https://images.unsplash.com/photo-1587293852726-70cdb56c2866?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=872&q=80" alt="Warehouse image">
{% endblock displayImage %}

{% comment %} 
{% block styles %}
    <link rel="stylesheet" href="{% static 'app_frontend/css/accounts.css' %}">
{% endblock styles %} {% endcomment %}

{% block formContainer %}
    
    <div class="row justify-content-center">
        <div class="text-center"><p id="form-header-label">Confirm OTP</p></div>
    </div>

    <form id="forgot-password-form" action={% url 'app_account:confirm-otp-forgot-password' %}>

        
        <div class="label-container">
            <p>Email:&nbsp;<p id="email"></p></p>
        </div>
        
        

        <!-- otp Input Fied -->
        <div class="form-group mb-3">
            <input type="text" class="form-control" id="otp-input"  placeholder="Enter the OTP" autocomplete="off">
        </div>

        <p id="errors-para-confirm-otp"></p>

        <div class="row justify-content-center">
            <div class="text-center"><button type="submit" class="btn btn-md btn-warning submit-btn">Confirm</button></div>
        </div>

        <input type="hidden" id="Url" data-url="{% url 'app_frontend:reset-password' %}" />
    </form>

{% endblock formContainer %}


{% block scripts %}

    <script>
        $( document ).ready(function() {
            $("#email").html(window.localStorage.getItem("email"))

            $("#forgot-password-form").submit(function(event){
                event.preventDefault(); // Prevent actual form submit

                var form = $(this);
                var url = form.attr('action');
                console.log(typeof(form.serialize()));
                console.log(form.serialize());

                var formdata = {
                    email: window.localStorage.getItem("email"),
                    otp: $("#otp-input").val(),
                    device_type: "I",
                    device_token: "",
                };

                $.ajax({
                    type: "POST",
                    url: url,
                    data: formdata,
                    success: function(json_data){
                        console.log(json_data);
                        if(json_data['success']===true){
                            window.localStorage.setItem("token", json_data['data']['token'])
                            $("#errors-para-forgot-password").html("");
                            $("#success-para-forgot-password").html(json_data['message']);
                            // redirect to the change password Page
                            var url = $("#Url").attr("data-url");
                            window.location.href = url;

                        }
                
                    },
                    error: function(json_data){
                        console.log(json_data['responseJSON'])
                        if(json_data['responseJSON']['success']===false){
                            $("#errors-para-confirm-otp").html(json_data['responseJSON']['message']);
                            // $("#success-para-forgot-password").html("");
                        }
                        //console.log(json_data['responseJSON']['non_field_errors']);
                        //var non_field_errors = json_data['responseJSON']['non_field_errors'];

                        //for(let i=0; i<non_field_errors.length; i++){
                        //    console.log(non_field_errors[i]);
                        //}

                        //for(let i=0; i<non_field_errors.length; i++){
                        //    console.log(non_field_errors[i]);
                        //}
                    }
                });


            });

        });

        
    </script> 

{% endblock scripts %}

app_frontend/templates/app_frontend/forgot_password.html
{% extends 'accounts_base.html' %}
{% load static %}

{% block title %}Forgot Password{% endblock title %}
{% block loginActiveStatus %}{% endblock loginActiveStatus %}
{% block displayImage %}
    <img src="https://images.unsplash.com/photo-1587293852726-70cdb56c2866?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=872&q=80" alt="Warehouse image">
{% endblock displayImage %}

{% comment %} 
{% block styles %}
    <link rel="stylesheet" href="{% static 'app_frontend/css/accounts.css' %}">
{% endblock styles %} {% endcomment %}

{% block formContainer %}
    
    <div class="row justify-content-center">
        <div class="text-center"><p id="form-header-label">Forgot Password</p></div>
    </div>

    <form id="forgot-password-form" action={% url 'app_account:forgot-password' %}>

        <!-- E-mail Input Fied -->
        <div class="form-group mb-3">
        <input type="email" class="form-control" id="email-input" aria-describedby="emailHelp" placeholder="Enter your email" autocomplete="off">
        <small id="emailHelp" class="form-text text-muted"></small>
        </div>

        <p id="errors-para-forgot-password"></p>
        <p id="success-para-forgot-password"></p>

        <div class="row justify-content-center">
            <div class="text-center"><button type="submit" class="btn btn-md btn-warning submit-btn">Submit</button></div>
        </div>

        <input type="hidden" id="Url" data-url="{% url 'app_frontend:confirm-otp' %}" />

    </form>

{% endblock formContainer %}


{% block scripts %}

    <script>
        $( document ).ready(function() {
            //scripts go here

            $("#forgot-password-form").submit(function(event){
                event.preventDefault(); // Prevent actual form submit

                var form = $(this);
                var url = form.attr('action');
                console.log(typeof(form.serialize()));
                console.log(form.serialize());

                var formdata = {
                    email: $("#email-input").val(),
                };

                $.ajax({
                    type: "POST",
                    url: url,
                    data: formdata,
                    success: function(json_data){
                        console.log(json_data);
                        if(json_data['success']===true){
                            window.localStorage.setItem("email", $("#email-input").val())
                            $("#errors-para-forgot-password").html("");
                            $("#success-para-forgot-password").html(json_data['message']);
                            // redirect to the confirm_otp Page
                            var url = $("#Url").attr("data-url");
                            window.location.href = url;

                        }
                        
                    },
                    error: function(json_data){
                        console.log(json_data['responseJSON'])
                        if(json_data['responseJSON']['success']===false){
                            $("#errors-para-forgot-password").html(json_data['responseJSON']['message']);
                            $("#success-para-forgot-password").html("");
                        }
                        //console.log(json_data['responseJSON']['non_field_errors']);
                          //for(let i=0; i<non_field_errors.length; i++){
                        //    console.log(non_field_errors[i]);
                        //}

                        //for(let i=0; i<non_field_errors.length; i++){
                        //    console.log(non_field_errors[i]);
                        //}
                    }
                });


            });

        });

        
    </script> 

{% endblock scripts %}

app_frontend/templates/app_frontend/login.html
{% extends 'accounts_base.html' %}
{% load static %}

{% block title %}Log In{% endblock title %}
{% block loginActiveStatus %}active{% endblock loginActiveStatus %}
{% block displayImage %}
    <img src="https://images.unsplash.com/photo-1587293852726-70cdb56c2866?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=872&q=80" alt="Warehouse image">
{% endblock displayImage %}

{% comment %} 
{% block styles %}
    <link rel="stylesheet" href="{% static 'app_frontend/css/accounts.css' %}">
{% endblock styles %} {% endcomment %}

{% block formContainer %}
    
    <div class="row justify-content-center">
        <div class="text-center form-heading"><p id="form-header-label">Log In</p></div>
    </div>

    <form id="login-form" action={% url 'app_account:login' %}>

        <!-- E-mail Input Fied -->
        <div class="form-group mb-3">
        <input type="email" class="form-control" id="email-input" aria-describedby="emailHelp" placeholder="Enter email" autocomplete="off">
        <small id="emailHelp" class="form-text text-muted"></small>
        </div>

        <!-- Password Input Field -->
        <div class="form-group mb-3">
        <input type="password" class="form-control" id="password-input" placeholder="Password" autocomplete="off">
        </div>
        <p id="errors-para"></p>

        <div class="forgotPasswordContainer"><a href={% url 'app_frontend:forgot-password' %}><p> Forgot Password? </p></a></div>

        <div class="row justify-content-center">
            <div class="text-center"><button type="submit" class="btn btn-md btn-warning submit-btn">Log In</button></div>
        </div>
    </form>

{% endblock formContainer %}


{% block scripts %}

    <script>
        $( document ).ready(function() {
            //scripts go here
            const BASE_URL = "127.0.0.1:8000";
            // const BASE_URL = $("#Url").attr("data-url");

            $("#login-form").submit(function(event){
                event.preventDefault(); // Prevent actual form submit

                var form = $(this);
                var url = form.attr('action');
                console.log(typeof(form.serialize()));
                console.log(form.serialize());

                var formdata = {
                    name: $("#id_name").val(),
                    email: $("#email-input").val(),
                    password:$("#password-input").val(),
                    device_type:"w",
                    device_token:"",
                };

                $.ajax({
                    type: "POST",
                    url: url,
                    data: formdata,
                    success: function(json_data){
                        console.log(json_data['data']['token']);
                        if(json_data['success']===true){
                            window.localStorage.setItem('token', json_data['data']['token']);
                            window.localStorage.setItem('user_id', json_data['data']['user']['id']);
                            window.localStorage.setItem('user_email', json_data['data']['user']['email']);
                            // console.log("TOKEN FROM LS",window.localStorage.getItem("token"));
                            // console.log("BASE_URL = "+ BASE_URL);
                            // redirect to the main page
                            window.location.href = "//" + BASE_URL;
                        }
                        
                    },
                    error: function(json_data){
                        console.log(json_data['responseJSON'])
                        if(json_data['responseJSON']['success']===false){
                            $("#errors-para").html(json_data['responseJSON']['message']);
                        }
                    }
                });


            });

        });

        
    </script> 

{% endblock scripts %}

app_frontend/templates/app_frontend/reset_password.html
{% extends 'accounts_base.html' %}
{% load static %}

{% block title %}Reset Password{% endblock title %}
{% block loginActiveStatus %}{% endblock loginActiveStatus %}
{% block displayImage %}
    <img src="https://images.unsplash.com/photo-1587293852726-70cdb56c2866?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=872&q=80" alt="Warehouse image">
{% endblock displayImage %}

{% comment %} 
{% block styles %}
    <link rel="stylesheet" href="{% static 'app_frontend/css/accounts.css' %}">
{% endblock styles %} {% endcomment %}

{% block formContainer %}
    
    <div class="row justify-content-center">
        <div class="text-center"><p id="form-header-label">Reset Password</p></div>
    </div>

    <form id="reset-password-form" action={% url 'app_account:reset-password' %}>

        <div class="label-container">
            <p>Email:&nbsp;<p id="email"></p></p>
        </div>

        <!-- Password Input Field -->
        <div class="form-group mb-3">
            <input type="password" class="form-control" id="password-input" placeholder="Password" autocomplete="off">
        </div>

        <!-- Password Input Field -->
        <div class="form-group mb-3">
            <input type="password" class="form-control" id="confirm-password-input" placeholder="Confirm Password" autocomplete="off">
        </div>

        <p id="errors-para-reset-password"></p>

        <div class="row justify-content-center">
            <div class="text-center"><button type="submit" class="btn btn-md btn-warning submit-btn">Submit</button></div>
        </div>

        <input type="hidden" id="Url" data-url="{% url 'app_frontend:login' %}" />
    </form>

{% endblock formContainer %}


{% block scripts %}

    <script>
        $( document ).ready(function() {

            var BASE_URL = "127.0.0.1:8000";

            $("#email").html(window.localStorage.getItem("email"))
            console.log(window.localStorage.getItem("token"));

            var token = "token " + window.localStorage.getItem("token");

            $("#reset-password-form").submit(function(event){
                event.preventDefault(); // Prevent actual form submit

                var form = $(this);
                var url = form.attr('action');
                console.log(typeof(form.serialize()));
                console.log(form.serialize());

                var formdata = {
                    password: $("#password-input").val(),
                    confirm_password: $("#confirm-password-input").val(),
                };

                $.ajax({
                    type: "POST",
                    url: url,
                    beforeSend: function (xhr) {
                        xhr.setRequestHeader('Authorization', token);
                    },
                    
                    data: formdata,
                    success: function(json_data){
                        console.log(json_data);
                        if(json_data['success']===true){
                            window.localStorage.setItem("token", json_data['data']['token'])
                            $("#errors-para-forgot-password").html("");
                            // $("#success-para-forgot-password").html(json_data['message']);
                            // redirect to the change password Page
                            alert("Your password has been changed successfully.");
                            window.localStorage.removeItem("token");
                            var url = $("#Url").attr("data-url");
                            window.location.href = "//" + BASE_URL + url;

                        }
                
                    },
                    error: function(json_data){
                        console.log(json_data['responseJSON'])
                        if(json_data['responseJSON']['success']===false){
                            $("#errors-para-reset-password").html(json_data['responseJSON']['message']);
                            // $("#success-para-forgot-password").html("");
                        }

                        else if(json_data['responseJSON']['detail']==="Invalid token"){
                            $("#errors-para-reset-password").html('Session Expired');
                        }
                        //console.log(json_data['responseJSON']['non_field_errors']);
                        //var non_field_errors = json_data['responseJSON']['non_field_errors'];

                        //for(let i=0; i<non_field_errors.length; i++){
                        //    console.log(non_field_errors[i]);
                        //}

                        //for(let i=0; i<non_field_errors.length; i++){
                        //    console.log(non_field_errors[i]);
                        //}
                    }
                });


            });

        });

        
    </script> 

{% endblock scripts %}