app_account/urls.py
from django.urls import URLPattern, path
from knox import views as knox_views

from .views import (
    CreateUser,
    LoginView,
    LogoutView,
    confirm_email,
    forgot_password,
    confirm_otp_forgot_password,
    ChangePasswordView,
    reset_password,
    activate_user_account_by_admin,
    PartialUpdateUser,
    GetUserDetails,
    GetAllUsers,
    GetLoginUserDetails,
)

app_name = "app_account"

urlpatterns = [
    path("register/", CreateUser.as_view(), name="register"),
    path("login/", LoginView.as_view(), name="login"),
    # path('logout/', knox_views.LogoutView.as_view(), name='knox_logout'),
    path("logout/", LogoutView.as_view(), name="logout"),
    path(
        "activate-user-account_by_admin/<int:pk>/",
        activate_user_account_by_admin,
        name="activate-user-account_by_admin",
    ),
    path(
        "confirm-email/<str:uidb64>/<str:token>/", confirm_email, name="confirm-email"
    ),
    path("forgot-password/", forgot_password, name="forgot-password"),
    path(
        "confirm-otp-forgot-password/",
        confirm_otp_forgot_password,
        name="confirm-otp-forgot-password",
    ),
    path("reset-password/", reset_password, name="reset-password"),
    path("change-password/", ChangePasswordView.as_view(), name="change-password"),
    path("update/", PartialUpdateUser.as_view(), name="update"),
    path("get-login-user-details/", GetLoginUserDetails.as_view(), name ="get-login-user-details"),
    path("get-all-users/", GetAllUsers.as_view(), name ="get-all-users"),
    path("get-user-details/<int:pk>/", GetUserDetails.as_view(), name ="get-user-details"),

]

app_temp/urls.py
from django.urls import URLPattern, path
from knox import views as knox_views

from .views import (
    TempCreate
)

app_name = "app_temp"

urlpatterns = [
    path("temp-create/", TempCreate.as_view(), name="temp-create"),

]

inventory_core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [ 
    path('api/', include("app_products.urls")),
    path('api/', include("app_account.urls")),
    path('', include("app_frontend.urls")),
    path('api/', include("app_temp.urls")),
    path('admin/', admin.site.urls),
    # path('api/auth/', include('knox.urls')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),                                                 

]


# Adding the static urls
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock title %}</title>

    <link rel="stylesheet" href="{% static 'css/base.css' %}" />

    <!-- Styles block to add different css files to different templates -->
    {% block styles %} {% endblock styles %}

    <!-- ===== Bootstrap CSS ===== -->
    <!-- <link rel="stylesheet" href="{% static 'lib/bootstrap/css/bootstrap.min.css' %}"> -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"
      crossorigin="anonymous"
    />

    <!-- Jquery ui -->
    <link
      rel="stylesheet"
      href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css"
    />
  </head>
  <body>
    <!-- <input type="hidden" id="base-url" data-url="127.0.0.1:8000" /> -->
    <!-- <input type="hidden" id="base-url" data-url="https://127.0.0.1:8000/" /> -->
    <!-- Include Header Here -->
    {% block header %} {% endblock header %}

    <!-- Content Block -->
    {% block content %}{% endblock content %}

    <!-- Include Footer Here -->
    {% block footer %} {% endblock footer %}

    <!-- ==============================
        Required JS Files
    =============================== -->

    <!-- Bootstrap bundle with jquery and popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
      crossorigin="anonymous"
    ></script>

    <!-- Jquery -->
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>

    <!-- Jquery UI js -->
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>

    <!-- ===== jQuery ===== -->
    <!-- <script src="{% static 'lib/jquery/jquery-3.6.0.min.js' %}"></script> -->

    <!-- ===== Bootstrap js ===== -->
    <!-- <script src="{% static 'lib/bootstrap/js/bootstrap.min.js' %}"></script> -->

    <!-- ===== Popper js ===== -->
    <!-- <script src="{% static 'lib/popper-js/popper.min.js' %}"></script> -->

    <!-- Scripts block to add different js files to different templates -->
    {% block scripts %} {% endblock scripts %}
  </body>
</html>

templates/email_approve_user_by_admin.html
{% autoescape off %}
Hi {{ admin_user.first_name }},
Please click on the link to Approve the user with the following details
Email: {{ user_email }}
Name: {{ user_name}}
Gender: {{ user_gender }}
DOB: {{ user_dob }}
Creation date: {{ user.created_on }}

http://{{ domain }}{% url 'app_account:activate-user-account_by_admin' pk=user_id %}
{% endautoescape %}

templates/email_confirmation_template.html
{% autoescape off %}
Hi {{ user.first_name }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'app_account:confirm-email' uidb64=uid token=token %}
{% endautoescape %}

templates/forgot_password_otp_template.html
{% autoescape off %}
Hi {{ user.username }},
Use the followong OTP to reset your password
OTP : {{otp}}
{% endautoescape %}